spring.application.name=url-shortener
spring.application.version=${APP_VERSION:development}
logging.structured.format.console=logstash
logging.structured.json.add.service=${spring.application.name}
logging.structured.json.add.serviceVersion=${spring.application.version}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.datasource.hikari.connection-timeout=250
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoints.web.exposure.include=metrics
management.metrics.tags.service=${spring.application.name}
