spring.application.name=url-shortener
spring.application.version=${APP_VERSION:development}
logging.structured.format.console=logstash
logging.structured.json.add.service=${spring.application.name}
logging.structured.json.add.serviceVersion=${spring.application.version}
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.datasource.hikari.connection-timeout=250
spring.jackson.deserialization.fail-on-unknown-properties=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
management.endpoints.web.exposure.include=health,metrics,info
management.metrics.tags.service=${spring.application.name}
url-shortener.cache.max-entries=10000
url-shortener.redis.required=true
