CREATE TABLE links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(10) NOT NULL,
    destination_url TEXT NOT NULL,
    analytics_token_hash BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_links_short_code UNIQUE (short_code),
    CONSTRAINT ck_links_destination_length CHECK (char_length(destination_url) <= 4096)
);
