CREATE TABLE click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id BIGINT NOT NULL REFERENCES links(id) ON DELETE RESTRICT,
    occurred_at TIMESTAMPTZ NOT NULL,
    traffic_class VARCHAR(24) NOT NULL,
    CONSTRAINT ck_click_events_traffic_class CHECK (traffic_class IN ('SUSPECTED_AUTOMATED', 'UNCLASSIFIED'))
);
CREATE INDEX ix_click_events_link_time ON click_events (link_id, occurred_at);
CREATE INDEX ix_click_events_occurred_at ON click_events (occurred_at);
